//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreatPizza.Server.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreatPizzaDbContext : DbContext
    {
        public GreatPizzaDbContext()
            : base("name=GreatPizzaDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pizza> Pizza { get; set; }
        public virtual DbSet<PizzaTopings> PizzaTopings { get; set; }
        public virtual DbSet<Toping> Toping { get; set; }
        public virtual DbSet<Log> Log { get; set; }
    }
}
